# Generated by Django 4.2.11 on 2024-03-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_verified_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ver_code',
            field=models.CharField(blank=True, null=True, verbose_name='код верификации'),
        ),
    ]
