# Generated by Django 5.0.2 on 2024-03-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_manufactured_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100, verbose_name='заголовок блога')),
                ('blog_slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='blog_slug')),
                ('blog_content', models.TextField(verbose_name='содержимое блога')),
                ('blog_preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='превью блога')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('is_publication', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('views_count', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ('created_at',),
            },
        ),
    ]
