# Generated by Django 5.0.2 on 2024-03-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='просмотры'),
        ),
    ]
