# Generated by Django 4.2.11 on 2024-04-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_version_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='is_publish',
        ),
    ]
